# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt Berridge - Freelance front end developer based in Berlin
description: > # this means to ignore newlines until "baseurl:"
  I’m a freelance front end developer> based in Berlin with a background in modular CSS architecture, but who writes mostly JavaScript these days. I've also got a pretty good eye for design both on and off the web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mattberridge.github.io" # the base hostname & protocol for your site
social-icons:
  - title: Twitter
    url: https://twitter.com/mattberridge
    print-text: twitter.com/mattberridge
    id: twitter
  - title: Github
    url: https://github.com/mattboon
    print-text: github.com/mattboon
    id: github
  - title: LinkedIn
    url: http://linkedin.com/in/mattakaboon
    print-text: linkedin.com/in/mattakaboon
    id: linkedin
  - title: Instagram
    url: https://instagram.com/boon
    print-text: instagram.com/boon
    id: instagram
  - title: Soundcloud
    url: https://soundcloud.com/mattboon
    print-text: soundcloud.com/mattboon
    id: soundcloud
  - title: Skype
    url: skype:boonmattberridge?call
    print-text: boonmattberridge
    id: skype

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Server Config options
livereload: true

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
  - bourbon
