# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Matt Berridge - Freelance front end developer based in Berlin
description: > # this means to ignore newlines until "baseurl:"
  I’m a freelance front end developer> based in Berlin with a background in modular CSS architecture, but who writes mostly JavaScript these days. I've also got a pretty good eye for design both on and off the web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mattberridge.github.io" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Server Config options
livereload: true

# Autoprefixing
autoprefixer:
  browsers:
  - last 5 versions

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-autoprefixer
